
const currencyList = [
  {"country": "Afghanistan", "currency": "Afghani", "abbreviation": "AFN"},
  {"country": "Albania", "currency": "Lek", "abbreviation": "ALL"},
  {"country": "Algeria", "currency": "Dinar", "abbreviation": "DZD"},
  {"country": "Andorra", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Angola", "currency": "Kwanza", "abbreviation": "AOA"},
  {"country": "Argentina", "currency": "Peso", "abbreviation": "ARS"},
  {"country": "Armenia", "currency": "Dram", "abbreviation": "AMD"},
  {"country": "Australia", "currency": "Dollar", "abbreviation": "AUD"},
  {"country": "Austria", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Azerbaijan", "currency": "Manat", "abbreviation": "AZN"},
  {"country": "Bahamas", "currency": "Dollar", "abbreviation": "BSD"},
  {"country": "Bahrain", "currency": "Dinar", "abbreviation": "BHD"},
  {"country": "Bangladesh", "currency": "Taka", "abbreviation": "BDT"},
  {"country": "Barbados", "currency": "Dollar", "abbreviation": "BBD"},
  {"country": "Belarus", "currency": "Belarusian Ruble", "abbreviation": "BYN"},
  {"country": "Belgium", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Belize", "currency": "Dollar", "abbreviation": "BZD"},
  {"country": "Benin", "currency": "CFA Franc BCEAO", "abbreviation": "XOF"},
  {"country": "Bhutan", "currency": "Ngultrum", "abbreviation": "BTN"},
  {"country": "Bolivia", "currency": "Boliviano", "abbreviation": "BOB"},
  {
    "country": "Bosnia and Herzegovina",
    "currency": "Convertible Mark",
    "abbreviation": "BAM"
  },
  {"country": "Botswana", "currency": "Pula", "abbreviation": "BWP"},
  {"country": "Brazil", "currency": "Real", "abbreviation": "BRL"},
  {"country": "Brunei", "currency": "Dollar", "abbreviation": "BND"},
  {"country": "Bulgaria", "currency": "Lev", "abbreviation": "BGN"},
  {
    "country": "Burkina Faso",
    "currency": "CFA Franc BCEAO",
    "abbreviation": "XOF"
  },
  {"country": "Burundi", "currency": "Burundi Franc", "abbreviation": "BIF"},
  {"country": "Cabo Verde", "currency": "Escudo", "abbreviation": "CVE"},
  {"country": "Cambodia", "currency": "Riel", "abbreviation": "KHR"},
  {"country": "Cameroon", "currency": "CFA Franc BEAC", "abbreviation": "XAF"},
  {"country": "Canada", "currency": "Dollar", "abbreviation": "CAD"},
  {
    "country": "Central African Republic",
    "currency": "CFA Franc BEAC",
    "abbreviation": "XAF"
  },
  {"country": "Chad", "currency": "CFA Franc BEAC", "abbreviation": "XAF"},
  {"country": "Chile", "currency": "Peso", "abbreviation": "CLP"},
  {"country": "China", "currency": "Yuan Renminbi", "abbreviation": "CNY"},
  {"country": "Colombia", "currency": "Peso", "abbreviation": "COP"},
  {"country": "Comoros", "currency": "Comorian Franc", "abbreviation": "KMF"},
  {"country": "Congo", "currency": "CFA Franc BEAC", "abbreviation": "XAF"},
  {"country": "Congo", "currency": "Congolese Franc", "abbreviation": "CDF"},
  {"country": "Costa Rica", "currency": "Colon", "abbreviation": "CRC"},
  {"country": "Croatia", "currency": "Kuna", "abbreviation": "HRK"},
  {"country": "Cuba", "currency": "Peso", "abbreviation": "CUP"},
  {"country": "Cyprus", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Czech Republic", "currency": "Koruna", "abbreviation": "CZK"},
  {"country": "Denmark", "currency": "Krone", "abbreviation": "DKK"},
  {"country": "Djibouti", "currency": "Djibouti Franc", "abbreviation": "DJF"},
  {"country": "Dominican Republic", "currency": "Peso", "abbreviation": "DOP"},
  {"country": "East Timor", "currency": "Dollar", "abbreviation": "USD"},
  {"country": "Ecuador", "currency": "Dollar", "abbreviation": "USD"},
  {"country": "Egypt", "currency": "Pound", "abbreviation": "EGP"},
  {"country": "El Salvador", "currency": "Dollar", "abbreviation": "USD"},
  {
    "country": "Equatorial Guinea",
    "currency": "CFA Franc BEAC",
    "abbreviation": "XAF"
  },
  {"country": "Eritrea", "currency": "Nakfa", "abbreviation": "ERN"},
  {"country": "Estonia", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Eswatini", "currency": "Lilangeni", "abbreviation": "SZL"},
  {"country": "Ethiopia", "currency": "Birr", "abbreviation": "ETB"},
  {"country": "Fiji", "currency": "Dollar", "abbreviation": "FJD"},
  {"country": "Finland", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "France", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Gabon", "currency": "CFA Franc BEAC", "abbreviation": "XAF"},
  {"country": "Gambia", "currency": "Dalasi", "abbreviation": "GMD"},
  {"country": "Georgia", "currency": "Lari", "abbreviation": "GEL"},
  {"country": "Germany", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Ghana", "currency": "Cedi", "abbreviation": "GHS"},
  {"country": "Greece", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Guatemala", "currency": "Quetzal", "abbreviation": "GTQ"},
  {"country": "Guinea", "currency": "Guinean Franc", "abbreviation": "GNF"},
  {
    "country": "Guinea-Bissau",
    "currency": "CFA Franc BCEAO",
    "abbreviation": "XOF"
  },
  {"country": "Guyana", "currency": "Dollar", "abbreviation": "GYD"},
  {"country": "Haiti", "currency": "Gourde", "abbreviation": "HTG"},
  {"country": "Honduras", "currency": "Lempira", "abbreviation": "HNL"},
  {"country": "Hong Kong", "currency": "Dollar", "abbreviation": "HKD"},
  {"country": "Hungary", "currency": "Forint", "abbreviation": "HUF"},
  {"country": "Iceland", "currency": "Krona", "abbreviation": "ISK"},
  {"country": "India", "currency": "Rupee", "abbreviation": "INR"},
  {"country": "Indonesia", "currency": "Rupiah", "abbreviation": "IDR"},
  {"country": "Iran", "currency": "Rial", "abbreviation": "IRR"},
  {"country": "Iraq", "currency": "Dinar", "abbreviation": "IQD"},
  {"country": "Ireland", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Italy", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Jamaica", "currency": "Dollar", "abbreviation": "JMD"},
  {"country": "Japan", "currency": "Yen", "abbreviation": "JPY"},
  {"country": "Jordan", "currency": "Dinar", "abbreviation": "JOD"},
  {"country": "Kazakhstan", "currency": "Tenge", "abbreviation": "KZT"},
  {"country": "Kenya", "currency": "Shilling", "abbreviation": "KES"},
  {"country": "Kuwait", "currency": "Dinar", "abbreviation": "KWD"},
  {"country": "Kyrgyzstan", "currency": "Som", "abbreviation": "KGS"},
  {"country": "Laos", "currency": "Kip", "abbreviation": "LAK"},
  {"country": "Latvia", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Lebanon", "currency": "Pound", "abbreviation": "LBP"},
  {"country": "Lesotho", "currency": "Loti", "abbreviation": "LSL"},
  {"country": "Liberia", "currency": "Dollar", "abbreviation": "LRD"},
  {"country": "Libya", "currency": "Dinar", "abbreviation": "LYD"},
  {"country": "Lithuania", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Luxembourg", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Macao", "currency": "Pataca", "abbreviation": "MOP"},
  {
    "country": "Madagascar",
    "currency": "Malagasy Ariary",
    "abbreviation": "MGA"
  },
  {"country": "Malawi", "currency": "Kwacha", "abbreviation": "MWK"},
  {"country": "Malaysia", "currency": "Ringgit", "abbreviation": "MYR"},
  {"country": "Maldives", "currency": "Rufiyaa", "abbreviation": "MVR"},
  {"country": "Mali", "currency": "CFA Franc BCEAO", "abbreviation": "XOF"},
  {"country": "Malta", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Mauritania", "currency": "Ouguiya", "abbreviation": "MRU"},
  {"country": "Mauritius", "currency": "Rupee", "abbreviation": "MUR"},
  {"country": "Mexico", "currency": "Peso", "abbreviation": "MXN"},
  {"country": "Moldova", "currency": "Leu", "abbreviation": "MDL"},
  {"country": "Monaco", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Mongolia", "currency": "Tugrik", "abbreviation": "MNT"},
  {"country": "Montenegro", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Morocco", "currency": "Dirham", "abbreviation": "MAD"},
  {"country": "Mozambique", "currency": "Metical", "abbreviation": "MZN"},
  {"country": "Myanmar", "currency": "Kyat", "abbreviation": "MMK"},
  {"country": "Namibia", "currency": "Dollar", "abbreviation": "NAD"},
  {"country": "Nepal", "currency": "Rupee", "abbreviation": "NPR"},
  {"country": "Netherlands", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "New Zealand", "currency": "Dollar", "abbreviation": "NZD"},
  {"country": "Nicaragua", "currency": "Cordoba", "abbreviation": "NIO"},
  {"country": "Niger", "currency": "CFA Franc BCEAO", "abbreviation": "XOF"},
  {"country": "Nigeria", "currency": "Naira", "abbreviation": "NGN"},
  {"country": "North Korea", "currency": "Won", "abbreviation": "KPW"},
  {"country": "North Macedonia", "currency": "Denar", "abbreviation": "MKD"},
  {"country": "Norway", "currency": "Krone", "abbreviation": "NOK"},
  {"country": "Oman", "currency": "Rial", "abbreviation": "OMR"},
  {"country": "Pakistan", "currency": "Rupee", "abbreviation": "PKR"},
  {"country": "Palestine", "currency": "Israeli Shekel", "abbreviation": "ILS"},
  {"country": "Panama", "currency": "Balboa", "abbreviation": "PAB"},
  {"country": "Papua New Guinea", "currency": "Kina", "abbreviation": "PGK"},
  {"country": "Paraguay", "currency": "Guarani", "abbreviation": "PYG"},
  {"country": "Peru", "currency": "Sol", "abbreviation": "PEN"},
  {"country": "Philippines", "currency": "Peso", "abbreviation": "PHP"},
  {"country": "Poland", "currency": "Zloty", "abbreviation": "PLN"},
  {"country": "Portugal", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Qatar", "currency": "Riyal", "abbreviation": "QAR"},
  {"country": "Romania", "currency": "Leu", "abbreviation": "RON"},
  {"country": "Russia", "currency": "Ruble", "abbreviation": "RUB"},
  {"country": "Rwanda", "currency": "Rwanda Franc", "abbreviation": "RWF"},
  {
    "country": "Saint Kitts and Nevis",
    "currency": "Dollar",
    "abbreviation": "XCD"
  },
  {"country": "Saint Lucia", "currency": "Dollar", "abbreviation": "XCD"},
  {
    "country": "Saint Vincent and the Grenadines",
    "currency": "Dollar",
    "abbreviation": "XCD"
  },
  {"country": "Samoa", "currency": "Tala", "abbreviation": "WST"},
  {"country": "San Marino", "currency": "Euro", "abbreviation": "EUR"},
  {
    "country": "Sao Tome and Principe",
    "currency": "Dobra",
    "abbreviation": "STN"
  },
  {"country": "Saudi Arabia", "currency": "Riyal", "abbreviation": "SAR"},
  {"country": "Senegal", "currency": "CFA Franc BCEAO", "abbreviation": "XOF"},
  {"country": "Serbia", "currency": "Dinar", "abbreviation": "RSD"},
  {"country": "Seychelles", "currency": "Rupee", "abbreviation": "SCR"},
  {"country": "Sierra Leone", "currency": "Leone", "abbreviation": "SLL"},
  {"country": "Singapore", "currency": "Dollar", "abbreviation": "SGD"},
  {"country": "Slovakia", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Slovenia", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Solomon Islands", "currency": "Dollar", "abbreviation": "SBD"},
  {"country": "Somalia", "currency": "Shilling", "abbreviation": "SOS"},
  {"country": "South Africa", "currency": "Rand", "abbreviation": "ZAR"},
  {"country": "South Korea", "currency": "Won", "abbreviation": "KRW"},
  {"country": "South Sudan", "currency": "Pound", "abbreviation": "SSP"},
  {"country": "Spain", "currency": "Euro", "abbreviation": "EUR"},
  {"country": "Sri Lanka", "currency": "Rupee", "abbreviation": "LKR"},
  {"country": "Sudan", "currency": "Pound", "abbreviation": "SDG"},
  {"country": "Suriname", "currency": "Dollar", "abbreviation": "SRD"},
  {"country": "Sweden", "currency": "Krona", "abbreviation": "SEK"},
  {"country": "Switzerland", "currency": "Franc", "abbreviation": "CHF"},
  {"country": "Syria", "currency": "Pound", "abbreviation": "SYP"},
  {"country": "Taiwan", "currency": "Dollar", "abbreviation": "TWD"},
  {"country": "Tajikistan", "currency": "Somoni", "abbreviation": "TJS"},
  {"country": "Tanzania", "currency": "Shilling", "abbreviation": "TZS"},
  {"country": "Thailand", "currency": "Baht", "abbreviation": "THB"},
  {"country": "Timor-Leste", "currency": "US Dollar", "abbreviation": "USD"},
  {"country": "Togo", "currency": "CFA Franc BCEAO", "abbreviation": "XOF"},
  {"country": "Tonga", "currency": "Pa'anga", "abbreviation": "TOP"},
  {
    "country": "Trinidad and Tobago",
    "currency": "Dollar",
    "abbreviation": "TTD"
  },
  {"country": "Tunisia", "currency": "Dinar", "abbreviation": "TND"},
  {"country": "Turkey", "currency": "Lira", "abbreviation": "TRY"},
  {"country": "Turkmenistan", "currency": "Manat", "abbreviation": "TMT"},
  {"country": "Tuvalu", "currency": "Australian Dollar", "abbreviation": "AUD"},
  {"country": "Uganda", "currency": "Shilling", "abbreviation": "UGX"},
  {"country": "Ukraine", "currency": "Hryvnia", "abbreviation": "UAH"},
  {
    "country": "United Arab Emirates",
    "currency": "Dirham",
    "abbreviation": "AED"
  },
  {"country": "United Kingdom", "currency": "Pound", "abbreviation": "GBP"},
  {"country": "United States", "currency": "Dollar", "abbreviation": "USD"}, 
  {"country": "Uruguay", "currency": "Peso", "abbreviation": "UYU"},
  {"country": "Uzbekistan", "currency": "Som", "abbreviation": "UZS"},
  {"country": "Vanuatu", "currency": "Vatu", "abbreviation": "VUV"},
  {"country": "Venezuela", "currency": "Bolivar", "abbreviation": "VES"},
  {"country": "Vietnam", "currency": "Dong", "abbreviation": "VND"},
  {"country": "Yemen", "currency": "Rial", "abbreviation": "YER"},
  {"country": "Zambia", "currency": "Kwacha", "abbreviation": "ZMW"},
  {"country": "Zimbabwe", "currency": "Dollar", "abbreviation": "ZWL"}
];
